[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [
    { access = "read", path = "./images/" },
    { access = "read", path = "./broadcast" },
]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@solmate=lib/solmate/src/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[invariant]
runs = 64
depth = 64
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
