[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ffi = true
evm_version = "shanghai"

remappings=['foundry-huff/=lib/foundry-huff/src']

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
